Feature delete project
squad-14/projects pull request #11
Opened 2021-12-13 22:55 UTC by julitaras

2021-12-13 22:57 UTC, PradaJoaquin approved these changes

2021-12-13 22:59 UTC, Mauro-Rizzi requested changes

2021-12-13 22:59 UTC, Mauro-Rizzi commented on src/api/project/api/handler_project_api.go
> +// @Param        project body dto.Project true "Update a task"
Update a task deberia ser "Delete a Project"

2021-12-13 22:59 UTC, julitaras commented on src/api/project/api/handler_project_api.go
> +// @Param        project body dto.Project true "Update a task"
yesss

2021-12-13 23:06 UTC, Mauro-Rizzi requested changes

2021-12-13 23:06 UTC, Mauro-Rizzi commented on src/api/project/api/handler_project_api.go
> +// @Param        project body dto.Project true "Delete a task"
Fijate que quedo task en vez de project

2021-12-14 13:56 UTC, Mauro-Rizzi approved these changes

2021-12-14 14:41 UTC, merged