Feature/update state
squad-14/projects pull request #4
Opened 2021-12-05 22:31 UTC by PradaJoaquin

2021-12-07 15:59 UTC, ncontinanza approved these changes

2021-12-07 17:17 UTC, julitaras requested changes

2021-12-07 17:17 UTC, julitaras commented on src/api/config/project_handlers_api.go
> +func (r *SRV) AddProjectHandlers(db *gorm.DB) *SRV {
Porque esta creacion? Deberia esta todo en el mismo file con el task ! ya que el server solo llama al `AddHandler`

2021-12-07 17:17 UTC, julitaras commented on src/api/main.go
> +	srv.AddTaskHandlers(db).Run(settings.GetData())
No vamos a ir agregando aca todos los handler!

2021-12-07 17:17 UTC, julitaras commented on src/api/project/api/handler_project_api.go
> +		fmt.Println(err)
Si. no vamos a hacer nada con este error, ignoremoslo. en caso de que querramos comunicar eso. Hagamos un abort y devolvamos el error

2021-12-07 17:17 UTC, julitaras commented on src/api/project/api/handler_project_api.go
> +	g.BindJSON(&dp)
No verificamos si esta el state?

2021-12-07 17:17 UTC, julitaras commented on src/api/project/api/handler_project_api.go
>  func getValErr(e validator.ValidationErrors) string {
eliminar metodo no utilizado

2021-12-07 17:17 UTC, julitaras commented on src/api/config/project_handlers_api.go
> +	r.PATCH("/projects/:id/state", projectHandler.Patch)
Nuvamente si vamos a dejar que sea mas global y se mofique todo, cambiar el verbo y todo lo que ya charlamos. Sino dejesmoslo asi

2021-12-07 17:17 UTC, julitaras commented on src/api/project/repository/project_repository.go
> +		log.Printf("Error updating Project #{err}")
`Error updating Project #{err}"` -> `Error updating Project %v, err"`

2021-12-07 17:17 UTC, julitaras commented on src/api/project/repository/project_repository.go
> +		log.Printf("Error finding Project #{err}")
idem

2021-12-07 20:56 UTC, julitaras commented
Update el branch con main

2021-12-09 23:59 UTC, julitaras approved these changes

2021-12-10 00:23 UTC, julitaras commented on src/api/project/api/dto/project.go
> +type State string
Si vamos a tener los mismos estados que para la task pongamoslo en algun lado comun asi no tenemos codigo repetido

2021-12-10 01:07 UTC, merged