Feature/swagger
squad-14/projects pull request #7
Opened 2021-12-10 01:35 UTC by Mauro-Rizzi

2021-12-11 23:32 UTC, Mauro-Rizzi commented
Will update the documentation on the new api bindings when their pull requests are merged into main.

2021-12-13 02:29 UTC, julitaras approved these changes

2021-12-13 02:29 UTC, julitaras commented on src/api/config/handlers_api.go
> +// @host      localhost:8080
Luego deberiamos actualizar esto cuando hagamos el deploy en heroku. O ya poner el dominio de heroku

2021-12-13 02:30 UTC, julitaras commented
Please update with main and fix problems

2021-12-13 12:46 UTC, Mauro-Rizzi commented on src/api/config/handlers_api.go
> +// @host      localhost:8080
@AlexDaciuk Tenes el domain de heroku?

2021-12-13 22:11 UTC, julitaras requested changes

2021-12-13 22:11 UTC, julitaras commented on src/api/project/api/handler_project_api.go
> +// @Param        task body dto.Project true "Get all projects"
```suggestion
// @Param        project body dto.Project true "Get all projects"
```

2021-12-13 22:11 UTC, julitaras commented on src/api/project/api/handler_project_api.go
> +// @Param        task body dto.Project true "Get a project"
idem here.
```suggestion
// @Param        project body dto.Project true "Get a project"
```

2021-12-13 22:11 UTC, julitaras commented on src/api/project/api/handler_project_api.go
> +// @Param        task body dto.Project true "Create a project"
```suggestion
// @Param        project body dto.Project true "Create a project"
```

2021-12-13 22:11 UTC, julitaras commented on src/api/project/api/handler_project_api.go
> +// @Param        task body dto.Project true "Update a project's state"
```suggestion
// @Param        project body dto.Project true "Update a project's state"
```

2021-12-13 22:11 UTC, julitaras commented on src/api/project/api/handler_project_api.go
> +// @Param        task body dto.Project true "Create a project"
```suggestion
// @Param        project body dto.Project true "Create a project"
```

2021-12-13 22:17 UTC, julitaras approved these changes

2021-12-13 22:17 UTC, PradaJoaquin approved these changes

2021-12-13 22:18 UTC, merged